### ISSUE TITLE
print_standup_data should be part of the standup data structure

### ISSUE THREAD

**Issue by loginn** [badjr13/laydown#10]
It would make more sense for standup to impl its own printing mechanism. Maybe through `std::fmt::Display` ?

**Comment by badjr13** [comment]
Asking not to question your idea but to better understand. Can you elaborate on why this would make more sense? This project is a platform for me to learn Rust. Feel free to leave as much detail as possible.

**Comment by loginn** [comment]
There's a couple of reasons I think this makes sense

1- From a software design pov, we are doing extra I/O (opening the same file multiple times ) with no actual benefits. For example, `add_item` will call `data_file::write_to_file(file, self)` and then `print_standup_data(file)` which both open file handles on the filesystem. By using the data already loaded in `Standup`, you get improved performance. Obviously for such an app this is very little concern but it still bothers me :>

You could simply pass your standup instance to your `print_standup_data` function but that leads me to point 2  ->

2- Traits are an important part of rust and you get to practice working with traits ! You can use standard printing using `println!(standup)` which is kinda cool I guess.

**Comment by badjr13** [comment]
Excellent, thank you! I'll be working on this update soon.

**Comment by badjr13** [comment]
@loginn - Hey, would you be willing to review the PR attached to this branch? I'm curious if you have any suggestions for my implementation.

One thing I'm curious about is this:
```rust
❯ cargo check
warning: unused variable: `f`
  --> src/standup.rs:68:19
   |
68 |     fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
   |                   ^ help: if this is intentional, prefix it with an underscore: `_f`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: `laydown` (lib) generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
```

I used the [example from the Rust docs](https://doc.rust-lang.org/std/fmt/trait.Display.html) around implementing `Display` but I deviated slightly. I was able to get the results I wanted using `print()` instead of `write()` and I didn't have a need for the `f: &mut fmt::Formatter<'_>` argument. This leads me to believe that perhaps my implementation isn't ideal. Curious about your thoughts.
